import Vue from 'vue'
import Vuetify, {
  VApp,
  VAlert,
  VBreadcrumbs,
  VBtn,
  VCard,
  VCheckbox,
  VChip,
  VCombobox,
  VDataTable,
  VDatePicker,
  VDialog,
  VDivider,
  VFooter,
  VForm,
  VIcon,
  VImg,
  VInput,
  VList,
  VMenu,
  VNavigationDrawer,
  VPicker,
  VResponsive,
  VSelect,
  VSnackbar,
  VStepper,
  VSubheader,
  VTextarea,
  VTextField,
  VTimePicker,
  VToolbar,
  VPagination,
  
} from 'vuetify/lib'
import colors from 'vuetify/es5/util/colors'

Vue.use(Vuetify, {
  theme: {
    accent: colors.grey.darken3,
    secondary: colors.amber.darken3,
    info: '#5bc0de',
    warning: colors.amber.base,
    error: colors.deepOrange.accent4,
    success: '#5cb85c',
    primary: '#428bca'    
  },
  components: {
    VApp,
    VAlert,
    VBreadcrumbs,
    VBtn,
    VCard,
    VCheckbox,
    VChip,
    VCombobox,
    VDataTable,
    VDatePicker,
    VDialog,
    VDivider,
    VFooter,
    VForm,
    VImg,
    VIcon,    
    VInput,
    VList,
    VMenu,
    VNavigationDrawer,
    VPicker,
    VResponsive,
    VSelect,
    VSnackbar,
    VStepper,
    VSubheader,
    VTextarea,
    VTextField,
    VTimePicker,
    VToolbar,
    VPagination
  }
})
